# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Continuous'), (1, 'Fixed Time'), (2, 'Interval'), (3, 'Dialy'), (4, 'Weekly'), (5, 'Monthly')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'Realtime'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('interval', models.IntegerField(default=1)),
                ('unit', models.IntegerField(choices=[(0, 'Seconds'), (1, 'Minutes'), (2, 'Hours')], default=1)),
                ('last_performed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightSearchCronJob',
            fields=[
                ('cronjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cron.CronJob')),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('outbound', models.DateField()),
                ('inbound', models.DateField()),
                ('passengers', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('cron.cronjob',),
        ),
        migrations.AddField(
            model_name='cronjoblog',
            name='cronjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cron.CronJob'),
        ),
    ]
