#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7

env:
  - DJANGO=1.10

before_install:
  - export DJANGO_SETTINGS_MODULE=wanderit.settings
  - export PYTHONPATH=$HOME/builds/crodriguezanton/wanderit

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - python manage.py runserver
