# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skyscannerSDK', '0002_auto_20161008_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound', models.DateField()),
                ('inbound', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='skyscannerSDK.Place')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='skyscannerSDK.Place')),
            ],
        ),
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('abs_diff', models.FloatField(default=0)),
                ('rel_diff', models.FloatField(default=0)),
                ('abs_deriv', models.FloatField(default=0)),
                ('rel_deriv', models.FloatField(default=0)),
                ('has_min_extremum', models.BooleanField(default=False)),
                ('has_positive_change_of_concavity', models.BooleanField(default=False)),
                ('has_negative_change_of_concavity', models.BooleanField(default=False)),
                ('first', models.BooleanField(default=False)),
                ('prev_first', models.BooleanField(default=False)),
                ('last', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='SearchReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('mean_price', models.FloatField()),
                ('flight_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyscannerSDK.FlightSearch')),
                ('max_price_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_price_itinerary', to='skyscannerSDK.Itinerary')),
                ('min_price_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_price_itinerary', to='skyscannerSDK.Itinerary')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchreports.Report')),
            ],
        ),
        migrations.AddField(
            model_name='reportupdate',
            name='search_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searchreports.SearchReport'),
        ),
    ]
