# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('skyscannerSDK', '0002_auto_20161008_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_nights', models.IntegerField()),
                ('max_nights', models.IntegerField()),
                ('wiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WanderitUser')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='UserDestinationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyscannerSDK.Place')),
                ('wiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WanderitUser')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='UserRequestMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelrequests.UserDatesRequest')),
                ('destination_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelrequests.UserDestinationRequest')),
            ],
        ),
    ]
