# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelrequests', '0002_auto_20161010_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='cron',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cron.FlightSearchCronJob'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='searchreports.Report'),
        ),
        migrations.AlterField(
            model_name='userdatesrequest',
            name='max_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatesrequest',
            name='min_nights',
            field=models.IntegerField(default=0),
        ),
    ]
